# Generated by Django 5.0.1 on 2026-01-28 13:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(
                        help_text="Уникальный URL для ресторана",
                        max_length=200,
                        unique=True,
                        verbose_name="URL идентификатор",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="restaurants/logos/",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="restaurants/covers/",
                        verbose_name="Обложка",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                ("website", models.URLField(blank=True, verbose_name="Веб-сайт")),
                ("address", models.CharField(max_length=300, verbose_name="Адрес")),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                (
                    "country",
                    models.CharField(
                        default="Кыргызстан", max_length=100, verbose_name="Страна"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="KGS",
                        help_text="Код валюты (USD, EUR, KGS и т.д.)",
                        max_length=10,
                        verbose_name="Валюта",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="ru",
                        help_text="Язык меню по умолчанию",
                        max_length=10,
                        verbose_name="Язык",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Налог в процентах (например, 10 для 10%)",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Ставка налога (%)",
                    ),
                ),
                (
                    "service_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Сервисный сбор в процентах",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Сервисный сбор (%)",
                    ),
                ),
                (
                    "opening_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Время открытия"
                    ),
                ),
                (
                    "closing_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Время закрытия"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Доступен ли ресторан для заказов",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "allow_cash_payment",
                    models.BooleanField(
                        default=True,
                        help_text="Принимать оплату наличными",
                        verbose_name="Разрешить наличные",
                    ),
                ),
                (
                    "allow_qr_payment",
                    models.BooleanField(
                        default=True,
                        help_text="Принимать оплату через QR код",
                        verbose_name="Разрешить QR оплату",
                    ),
                ),
                (
                    "require_waiter_confirmation",
                    models.BooleanField(
                        default=True,
                        help_text="Официант должен подтвердить заказы с наличной оплатой",
                        verbose_name="Требуется подтверждение официанта",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_restaurants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ресторан",
                "verbose_name_plural": "Рестораны",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RestaurantSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Отправлять уведомления на email",
                        verbose_name="Email уведомления",
                    ),
                ),
                (
                    "sms_notifications",
                    models.BooleanField(
                        default=False,
                        help_text="Отправлять SMS уведомления",
                        verbose_name="SMS уведомления",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#007bff",
                        help_text="Цвет в формате HEX (#000000)",
                        max_length=7,
                        verbose_name="Основной цвет",
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#6c757d",
                        help_text="Цвет в формате HEX (#000000)",
                        max_length=7,
                        verbose_name="Вторичный цвет",
                    ),
                ),
                (
                    "welcome_message",
                    models.TextField(
                        blank=True,
                        help_text="Сообщение, которое видят гости при сканировании QR кода",
                        verbose_name="Приветственное сообщение",
                    ),
                ),
                (
                    "footer_text",
                    models.TextField(
                        blank=True,
                        help_text="Текст внизу страницы меню",
                        verbose_name="Текст в подвале",
                    ),
                ),
                (
                    "restaurant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="restaurants.restaurant",
                        verbose_name="Ресторан",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки ресторана",
                "verbose_name_plural": "Настройки ресторанов",
            },
        ),
    ]
