# Generated by Django 5.0.1 on 2026-01-28 13:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Название иконки (например: utensils, pizza-slice)",
                        max_length=50,
                        verbose_name="Иконка",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Чем меньше число, тем выше категория в списке",
                        verbose_name="Порядок сортировки",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_categories",
                        to="restaurants.restaurant",
                        verbose_name="Ресторан",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория меню",
                "verbose_name_plural": "Категории меню",
                "ordering": ["restaurant", "order", "name"],
                "unique_together": {("restaurant", "name")},
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="menu/items/",
                        verbose_name="Фото блюда",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Цена",
                    ),
                ),
                (
                    "cooking_time",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Примерное время приготовления в минутах",
                        null=True,
                        verbose_name="Время приготовления (мин)",
                    ),
                ),
                (
                    "calories",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Калорийность на порцию",
                        null=True,
                        verbose_name="Калорийность",
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Вес порции в граммах",
                        null=True,
                        verbose_name="Вес (г)",
                    ),
                ),
                (
                    "is_vegetarian",
                    models.BooleanField(default=False, verbose_name="Вегетарианское"),
                ),
                (
                    "is_vegan",
                    models.BooleanField(default=False, verbose_name="Веганское"),
                ),
                ("is_spicy", models.BooleanField(default=False, verbose_name="Острое")),
                (
                    "spicy_level",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="От 0 (не острое) до 5 (очень острое)",
                        validators=[django.core.validators.MaxValueValidator(5)],
                        verbose_name="Уровень остроты",
                    ),
                ),
                (
                    "is_chef_special",
                    models.BooleanField(
                        default=False, verbose_name="Рекомендация шефа"
                    ),
                ),
                (
                    "is_popular",
                    models.BooleanField(
                        default=False,
                        help_text="Часто заказываемое блюдо",
                        verbose_name="Популярное",
                    ),
                ),
                (
                    "allergens",
                    models.TextField(
                        blank=True,
                        help_text="Перечислите аллергены через запятую",
                        verbose_name="Аллергены",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Можно ли заказать блюдо сейчас",
                        verbose_name="Доступно",
                    ),
                ),
                (
                    "stock_quantity",
                    models.IntegerField(
                        blank=True,
                        help_text="Оставьте пустым для неограниченного количества",
                        null=True,
                        verbose_name="Остаток",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="menu.menucategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция меню",
                "verbose_name_plural": "Позиции меню",
                "ordering": ["category", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MenuItemOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Например: Размер, Добавки",
                        max_length=100,
                        verbose_name="Название опции",
                    ),
                ),
                (
                    "choices",
                    models.JSONField(
                        help_text='Список вариантов в формате: [{"value": "small", "label": "Маленькая", "price_modifier": 0}]',
                        verbose_name="Варианты выбора",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="Необходимо ли выбрать опцию при заказе",
                        verbose_name="Обязательная",
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="menu.menuitem",
                        verbose_name="Позиция меню",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опция позиции меню",
                "verbose_name_plural": "Опции позиций меню",
            },
        ),
    ]
