# Generated by Django 5.0.1 on 2026-01-28 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("restaurants", "0001_initial"),
        ("tables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                help_text="Ресторан, к которому привязан пользователь (для владельцев и официантов)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="restaurants.restaurant",
                verbose_name="Ресторан",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="guestsession",
            name="table_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guest_sessions",
                to="tables.tablesession",
                verbose_name="Сессия столика",
            ),
        ),
    ]
