# Generated by Django 5.0.1 on 2026-01-28 13:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("tables", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ID платежа"
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("cash", "Наличные"),
                            ("qr", "QR код"),
                            ("card", "Карта"),
                            ("online", "Онлайн"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="Тип оплаты",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("processing", "Обрабатывается"),
                            ("completed", "Завершен"),
                            ("failed", "Ошибка"),
                            ("cancelled", "Отменен"),
                            ("refunded", "Возвращен"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="KGS", max_length=10, verbose_name="Валюта"
                    ),
                ),
                (
                    "payer_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Имя плательщика"
                    ),
                ),
                (
                    "payer_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Телефон плательщика"
                    ),
                ),
                (
                    "payer_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email плательщика"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="ID транзакции от платежной системы",
                        max_length=200,
                        verbose_name="ID транзакции",
                    ),
                ),
                (
                    "payment_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Дополнительные данные от платежной системы",
                        verbose_name="Данные платежа",
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Сумма возврата",
                    ),
                ),
                (
                    "refund_reason",
                    models.TextField(blank=True, verbose_name="Причина возврата"),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата возврата"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата завершения"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Примечания")),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Оплата конкретного заказа",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обработано",
                    ),
                ),
                (
                    "table_session",
                    models.ForeignKey(
                        blank=True,
                        help_text="Общая оплата за весь столик",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="tables.tablesession",
                        verbose_name="Сессия столика",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QRPaymentCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qr_code_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="payments/qr_codes/",
                        verbose_name="QR код",
                    ),
                ),
                (
                    "qr_data",
                    models.TextField(
                        help_text="URL или данные для QR кода оплаты",
                        verbose_name="Данные QR кода",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Срок действия"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_code",
                        to="payments.payment",
                        verbose_name="Платеж",
                    ),
                ),
            ],
            options={
                "verbose_name": "QR код оплаты",
                "verbose_name_plural": "QR коды оплаты",
            },
        ),
    ]
