# Generated by Django 5.0.1 on 2026-01-28 13:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Номер или название столика (например: A1, VIP-1)",
                        max_length=20,
                        verbose_name="Номер столика",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="Количество мест за столиком",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Вместимость",
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tables/qr_codes/",
                        verbose_name="QR код",
                    ),
                ),
                (
                    "qr_url",
                    models.CharField(
                        blank=True,
                        help_text="Генерируется автоматически",
                        max_length=500,
                        verbose_name="URL для QR кода",
                    ),
                ),
                (
                    "is_occupied",
                    models.BooleanField(
                        default=False,
                        help_text="Есть ли активная сессия за столиком",
                        verbose_name="Занят",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Доступен ли столик для использования",
                        verbose_name="Активен",
                    ),
                ),
                (
                    "zone",
                    models.CharField(
                        blank=True,
                        help_text="Зона размещения (Терраса, Основной зал, VIP и т.д.)",
                        max_length=100,
                        verbose_name="Зона",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Дополнительная информация о столике",
                        verbose_name="Описание",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="restaurants.restaurant",
                        verbose_name="Ресторан",
                    ),
                ),
            ],
            options={
                "verbose_name": "Столик",
                "verbose_name_plural": "Столики",
                "ordering": ["restaurant", "number"],
                "unique_together": {("restaurant", "number")},
            },
        ),
        migrations.CreateModel(
            name="TableSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_code",
                    models.CharField(
                        help_text="Уникальный код для подключения гостей",
                        max_length=50,
                        unique=True,
                        verbose_name="Код сессии",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время начала"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Время окончания"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Заметки официанта о столике/гостях",
                        verbose_name="Заметки",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="tables.table",
                        verbose_name="Столик",
                    ),
                ),
                (
                    "waiter",
                    models.ForeignKey(
                        blank=True,
                        help_text="Официант, обслуживающий столик",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="table_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Официант",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сессия столика",
                "verbose_name_plural": "Сессии столиков",
                "ordering": ["-started_at"],
            },
        ),
    ]
